title: World Domination - A 3 Step Process
author: Supreme Leader
email: Supreme.Leader503@domain.com
description: > # this means to ignore newlines until "baseurl:"
  blog to discuss the 3 steps of taking over the world and 
  how to handle the stress that comes with being a supreme leader

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
